### ISSUE TITLE
Update to lodash v3

### ISSUE THREAD

**Issue by d10** [d10/lodash-webbuilder#5]
~~Allows devs to test custom v3-pre builds before v3 is out.~~
Update site to use lodash v3.

**Comment by jdalton** [comment]
Time to update :)

**Comment by d10** [comment]
Yep, will try to do this on Friday.

**Comment by jdalton** [comment]
Ping.

**Comment by d10** [comment]
Now live at https://lodash-webbuilder-dev.herokuapp.com, please check all functionality before I merge into `master`.

**Comment by d10** [comment]
Closed by d3f12f49c5d331fbd8a2bcd1db13aaef4c506008.
